### PR TITLE
Make micromanager executable from other directories

### PR DESCRIPTION
**Pull request by Scriptkiddi**

### CODE REVIEW

**Review by IshaanDesai — COMMENTED** [review]
@Scriptkiddi can you show how one can run the micro-manager directly from the terminal after these changes are incorporated? I just tried this, I installed the code from your fork and tried to run it directly from the command line, but it did not work.

**Comment by Scriptkiddi** [comment]
could you try again? I currently dont have a working ubuntu machine

**Comment by Scriptkiddi** [comment]
@IshaanDesai all done now

**Review by IshaanDesai — APPROVED** [review]
Nice feature! Thanks for adding this :+1:

**Pull request merged**
