### PR TITLE
Change logging strategy and add new logging for adaptivity metrics

### PR DESCRIPTION
**Pull request by IshaanDesai**
This PR adds the following:

- A new logging framework with a dedicated `Logger` class. In this class, a logger is generated and logging options are provided for logging via one one rank, any rank of choice, or all ranks. Different types of logging are possible. Currently the options are `info` and `error`.
- **Breaking change**: changes the configuration parameter `config_file_name` to `precice_config_file_name` to differentiate it from the Micro Manager JSON configuration file.
- Add optional parameter `output_cpu_time` to `adaptivity_settings` which will output CPU time of the adaptivity computation on every rank. The data is written to preCICE with the intention of being exported. All the micro simulations (coupling vertices) on one rank will have the same scalar value of the adaptivity computation CPU time.
- **Breaking change**: Change the name of the diagnostics output `micro_sim_time` to `solve_cpu_time`.

Checklist:

- [x] I made sure that the CI passed before I ask for a review.
- [x] I added a summary of the changes (compared to the last release) in the `CHANGELOG.md`.
- [x] I will remember to squash-and-merge, providing a useful summary of the changes of this PR.

### CODE REVIEW

**Comment by Fujikawas** [comment]
Would be good to put the "number of active simulations" into a format which is more machine-readable than the current text style.

**Comment by uekerman** [comment]
Could https://github.com/precice/precice/issues/2015 be an alternative technical solution?

**Comment by IshaanDesai** [comment]
> Could [precice/precice#2015](https://github.com/precice/precice/issues/2015) be an alternative technical solution?

Potentially yes. I have implemented something very close to this, with additionally handling logging in parallel. Would it be possible to tell preCICE to log somethings only on one rank, and other things on all ranks? Also, such logging API would need to be added to the Python bindings.

**Comment by uekerman** [comment]
> Would it be possible to tell preCICE to log somethings only on one rank, and other things on all ranks?

Yes, this is part of the runtime configuration for the existing preCICE logging already now.

**Pull request merged**
